// ⚠️ ARCHIVO GENERADO AUTOMÁTICAMENTE — NO EDITAR MANUALMENTE
// Para agregar o quitar fotos/videos, modifica los archivos dentro de public/media/
// Este archivo se regenera cada vez que ejecutas `npm run build`.

import type { MediaItem } from './data';

/** Todos los medios (galería general = carpeta general + todos los grupos) */
export const GENERATED_ALL_MEDIA: MediaItem[] = [
  {
    id: "general-1",
    title: "Aaah",
    type: "photo",
    url: "/media/general/Aaah.webp",
    thumbnailUrl: "/media/general/Aaah.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-2",
    title: "Asi O Que",
    type: "photo",
    url: "/media/general/Asi o que.webp",
    thumbnailUrl: "/media/general/Asi o que.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-3",
    title: "Atiende",
    type: "photo",
    url: "/media/general/Atiende.webp",
    thumbnailUrl: "/media/general/Atiende.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-4",
    title: "Caray",
    type: "photo",
    url: "/media/general/Caray.webp",
    thumbnailUrl: "/media/general/Caray.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-5",
    title: "Con Ganas",
    type: "photo",
    url: "/media/general/Con ganas.webp",
    thumbnailUrl: "/media/general/Con ganas.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-6",
    title: "Concentrate",
    type: "photo",
    url: "/media/general/Concentrate.webp",
    thumbnailUrl: "/media/general/Concentrate.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-7",
    title: "Corre",
    type: "photo",
    url: "/media/general/Corre.webp",
    thumbnailUrl: "/media/general/Corre.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-8",
    title: "Cuando Dios Habla",
    type: "photo",
    url: "/media/general/Cuando Dios habla.webp",
    thumbnailUrl: "/media/general/Cuando Dios habla.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-9",
    title: "De Chill",
    type: "photo",
    url: "/media/general/De chill.webp",
    thumbnailUrl: "/media/general/De chill.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-10",
    title: "Hasta Abajo",
    type: "photo",
    url: "/media/general/Hasta abajo.webp",
    thumbnailUrl: "/media/general/Hasta abajo.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-11",
    title: "Listos",
    type: "photo",
    url: "/media/general/Listos.webp",
    thumbnailUrl: "/media/general/Listos.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-12",
    title: "Modo Campeon",
    type: "photo",
    url: "/media/general/Modo Campeon.webp",
    thumbnailUrl: "/media/general/Modo Campeon.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-13",
    title: "Que Dios Te Hable",
    type: "photo",
    url: "/media/general/Que Dios te hable.webp",
    thumbnailUrl: "/media/general/Que Dios te hable.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-14",
    title: "Que No Caiga",
    type: "photo",
    url: "/media/general/Que no caiga.webp",
    thumbnailUrl: "/media/general/Que no caiga.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-15",
    title: "Que",
    type: "photo",
    url: "/media/general/Que.webp",
    thumbnailUrl: "/media/general/Que.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-16",
    title: "Risas Y Mas",
    type: "photo",
    url: "/media/general/Risas y mas.webp",
    thumbnailUrl: "/media/general/Risas y mas.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-17",
    title: "Solo Un Toque",
    type: "photo",
    url: "/media/general/Solo un toque.webp",
    thumbnailUrl: "/media/general/Solo un toque.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-18",
    title: "Sonrie",
    type: "photo",
    url: "/media/general/Sonrie.webp",
    thumbnailUrl: "/media/general/Sonrie.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-19",
    title: "Ya Llegaaa",
    type: "photo",
    url: "/media/general/Ya llegaaa.webp",
    thumbnailUrl: "/media/general/Ya llegaaa.webp",
    groupColor: "general",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "blanco-1",
    title: "B1",
    type: "photo",
    url: "/media/grupos/blanco/b1.jpeg",
    thumbnailUrl: "/media/grupos/blanco/b1.jpeg",
    groupColor: "blanco",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "azul-1",
    title: "Az1",
    type: "photo",
    url: "/media/grupos/azul/az1.jpeg",
    thumbnailUrl: "/media/grupos/azul/az1.jpeg",
    groupColor: "azul",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "amarillo-1",
    title: "A1",
    type: "photo",
    url: "/media/grupos/amarillo/a1.jpeg",
    thumbnailUrl: "/media/grupos/amarillo/a1.jpeg",
    groupColor: "amarillo",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "turquesa-1",
    title: "T1",
    type: "photo",
    url: "/media/grupos/turquesa/t1.jpeg",
    thumbnailUrl: "/media/grupos/turquesa/t1.jpeg",
    groupColor: "turquesa",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "rojo-1",
    title: "R1",
    type: "photo",
    url: "/media/grupos/rojo/r1.jpeg",
    thumbnailUrl: "/media/grupos/rojo/r1.jpeg",
    groupColor: "rojo",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "verde-limon-1",
    title: "Vl1",
    type: "photo",
    url: "/media/grupos/verde-limon/vl1.jpeg",
    thumbnailUrl: "/media/grupos/verde-limon/vl1.jpeg",
    groupColor: "verde-limon",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "azul-gris-1",
    title: "Ag1",
    type: "photo",
    url: "/media/grupos/azul-gris/ag1.jpeg",
    thumbnailUrl: "/media/grupos/azul-gris/ag1.jpeg",
    groupColor: "azul-gris",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "rosado-1",
    title: "Rs1",
    type: "photo",
    url: "/media/grupos/rosado/rs1.jpeg",
    thumbnailUrl: "/media/grupos/rosado/rs1.jpeg",
    groupColor: "rosado",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "morado-1",
    title: "M1",
    type: "photo",
    url: "/media/grupos/morado/m1.jpeg",
    thumbnailUrl: "/media/grupos/morado/m1.jpeg",
    groupColor: "morado",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "cafe-1",
    title: "C1",
    type: "photo",
    url: "/media/grupos/cafe/c1.jpeg",
    thumbnailUrl: "/media/grupos/cafe/c1.jpeg",
    groupColor: "cafe",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "verde-1",
    title: "V1",
    type: "photo",
    url: "/media/grupos/verde/v1.jpeg",
    thumbnailUrl: "/media/grupos/verde/v1.jpeg",
    groupColor: "verde",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "celeste-1",
    title: "Ce1",
    type: "photo",
    url: "/media/grupos/celeste/ce1.jpeg",
    thumbnailUrl: "/media/grupos/celeste/ce1.jpeg",
    groupColor: "celeste",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "negro-1",
    title: "N1",
    type: "photo",
    url: "/media/grupos/negro/n1.jpeg",
    thumbnailUrl: "/media/grupos/negro/n1.jpeg",
    groupColor: "negro",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "vino-1",
    title: "Vi1",
    type: "photo",
    url: "/media/grupos/vino/vi1.jpeg",
    thumbnailUrl: "/media/grupos/vino/vi1.jpeg",
    groupColor: "vino",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  }
];

/** Solo medios de grupos específicos */
export const GENERATED_GROUP_MEDIA: MediaItem[] = [
  {
    id: "blanco-1",
    title: "B1",
    type: "photo",
    url: "/media/grupos/blanco/b1.jpeg",
    thumbnailUrl: "/media/grupos/blanco/b1.jpeg",
    groupColor: "blanco",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "azul-1",
    title: "Az1",
    type: "photo",
    url: "/media/grupos/azul/az1.jpeg",
    thumbnailUrl: "/media/grupos/azul/az1.jpeg",
    groupColor: "azul",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "amarillo-1",
    title: "A1",
    type: "photo",
    url: "/media/grupos/amarillo/a1.jpeg",
    thumbnailUrl: "/media/grupos/amarillo/a1.jpeg",
    groupColor: "amarillo",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "turquesa-1",
    title: "T1",
    type: "photo",
    url: "/media/grupos/turquesa/t1.jpeg",
    thumbnailUrl: "/media/grupos/turquesa/t1.jpeg",
    groupColor: "turquesa",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "rojo-1",
    title: "R1",
    type: "photo",
    url: "/media/grupos/rojo/r1.jpeg",
    thumbnailUrl: "/media/grupos/rojo/r1.jpeg",
    groupColor: "rojo",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "verde-limon-1",
    title: "Vl1",
    type: "photo",
    url: "/media/grupos/verde-limon/vl1.jpeg",
    thumbnailUrl: "/media/grupos/verde-limon/vl1.jpeg",
    groupColor: "verde-limon",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "azul-gris-1",
    title: "Ag1",
    type: "photo",
    url: "/media/grupos/azul-gris/ag1.jpeg",
    thumbnailUrl: "/media/grupos/azul-gris/ag1.jpeg",
    groupColor: "azul-gris",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "rosado-1",
    title: "Rs1",
    type: "photo",
    url: "/media/grupos/rosado/rs1.jpeg",
    thumbnailUrl: "/media/grupos/rosado/rs1.jpeg",
    groupColor: "rosado",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "morado-1",
    title: "M1",
    type: "photo",
    url: "/media/grupos/morado/m1.jpeg",
    thumbnailUrl: "/media/grupos/morado/m1.jpeg",
    groupColor: "morado",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "cafe-1",
    title: "C1",
    type: "photo",
    url: "/media/grupos/cafe/c1.jpeg",
    thumbnailUrl: "/media/grupos/cafe/c1.jpeg",
    groupColor: "cafe",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "verde-1",
    title: "V1",
    type: "photo",
    url: "/media/grupos/verde/v1.jpeg",
    thumbnailUrl: "/media/grupos/verde/v1.jpeg",
    groupColor: "verde",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "celeste-1",
    title: "Ce1",
    type: "photo",
    url: "/media/grupos/celeste/ce1.jpeg",
    thumbnailUrl: "/media/grupos/celeste/ce1.jpeg",
    groupColor: "celeste",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "negro-1",
    title: "N1",
    type: "photo",
    url: "/media/grupos/negro/n1.jpeg",
    thumbnailUrl: "/media/grupos/negro/n1.jpeg",
    groupColor: "negro",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "vino-1",
    title: "Vi1",
    type: "photo",
    url: "/media/grupos/vino/vi1.jpeg",
    thumbnailUrl: "/media/grupos/vino/vi1.jpeg",
    groupColor: "vino",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  }
];

export const GENERATED_COUNT = {
  total: 33,
  groups: 14,
  general: 19,
};
