// ⚠️ ARCHIVO GENERADO AUTOMÁTICAMENTE — NO EDITAR MANUALMENTE
// Para agregar o quitar fotos/videos, modifica los archivos dentro de public/media/
// Este archivo se regenera cada vez que ejecutas `npm run build`.

import type { MediaItem } from './data';

/** Todos los medios (galería general = carpeta general + todos los grupos) */
export const GENERATED_ALL_MEDIA: MediaItem[] = [
  {
    id: "general-1",
    title: "Gn1",
    type: "video",
    url: "/media/general/gn1.MP4",
    thumbnailUrl: "/media/general/gn1.MP4",
    groupColor: "rojo",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "general-2",
    title: "Gn2",
    type: "video",
    url: "/media/general/gn2.MP4",
    thumbnailUrl: "/media/general/gn2.MP4",
    groupColor: "rojo",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "blanco-1",
    title: "B1",
    type: "photo",
    url: "/media/grupos/blanco/b1.jpeg",
    thumbnailUrl: "/media/grupos/blanco/b1.jpeg",
    groupColor: "blanco",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "azul-1",
    title: "Az1",
    type: "photo",
    url: "/media/grupos/azul/az1.jpeg",
    thumbnailUrl: "/media/grupos/azul/az1.jpeg",
    groupColor: "azul",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "amarillo-1",
    title: "A1",
    type: "photo",
    url: "/media/grupos/amarillo/a1.jpeg",
    thumbnailUrl: "/media/grupos/amarillo/a1.jpeg",
    groupColor: "amarillo",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "turquesa-1",
    title: "T1",
    type: "photo",
    url: "/media/grupos/turquesa/t1.jpeg",
    thumbnailUrl: "/media/grupos/turquesa/t1.jpeg",
    groupColor: "turquesa",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "rojo-1",
    title: "R1",
    type: "photo",
    url: "/media/grupos/rojo/r1.jpeg",
    thumbnailUrl: "/media/grupos/rojo/r1.jpeg",
    groupColor: "rojo",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "verde-limon-1",
    title: "Vl1",
    type: "photo",
    url: "/media/grupos/verde-limon/vl1.jpeg",
    thumbnailUrl: "/media/grupos/verde-limon/vl1.jpeg",
    groupColor: "verde-limon",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "azul-gris-1",
    title: "Ag1",
    type: "photo",
    url: "/media/grupos/azul-gris/ag1.jpeg",
    thumbnailUrl: "/media/grupos/azul-gris/ag1.jpeg",
    groupColor: "azul-gris",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "rosado-1",
    title: "Rs1",
    type: "photo",
    url: "/media/grupos/rosado/rs1.jpeg",
    thumbnailUrl: "/media/grupos/rosado/rs1.jpeg",
    groupColor: "rosado",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "morado-1",
    title: "M1",
    type: "photo",
    url: "/media/grupos/morado/m1.jpeg",
    thumbnailUrl: "/media/grupos/morado/m1.jpeg",
    groupColor: "morado",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "cafe-1",
    title: "C1",
    type: "photo",
    url: "/media/grupos/cafe/c1.jpeg",
    thumbnailUrl: "/media/grupos/cafe/c1.jpeg",
    groupColor: "cafe",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "verde-1",
    title: "V1",
    type: "photo",
    url: "/media/grupos/verde/v1.jpeg",
    thumbnailUrl: "/media/grupos/verde/v1.jpeg",
    groupColor: "verde",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "celeste-1",
    title: "Ce1",
    type: "photo",
    url: "/media/grupos/celeste/ce1.jpeg",
    thumbnailUrl: "/media/grupos/celeste/ce1.jpeg",
    groupColor: "celeste",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "negro-1",
    title: "N1",
    type: "photo",
    url: "/media/grupos/negro/n1.jpeg",
    thumbnailUrl: "/media/grupos/negro/n1.jpeg",
    groupColor: "negro",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "vino-1",
    title: "Vi1",
    type: "photo",
    url: "/media/grupos/vino/vi1.jpeg",
    thumbnailUrl: "/media/grupos/vino/vi1.jpeg",
    groupColor: "vino",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  }
];

/** Solo medios de grupos específicos */
export const GENERATED_GROUP_MEDIA: MediaItem[] = [
  {
    id: "blanco-1",
    title: "B1",
    type: "photo",
    url: "/media/grupos/blanco/b1.jpeg",
    thumbnailUrl: "/media/grupos/blanco/b1.jpeg",
    groupColor: "blanco",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "azul-1",
    title: "Az1",
    type: "photo",
    url: "/media/grupos/azul/az1.jpeg",
    thumbnailUrl: "/media/grupos/azul/az1.jpeg",
    groupColor: "azul",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "amarillo-1",
    title: "A1",
    type: "photo",
    url: "/media/grupos/amarillo/a1.jpeg",
    thumbnailUrl: "/media/grupos/amarillo/a1.jpeg",
    groupColor: "amarillo",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "turquesa-1",
    title: "T1",
    type: "photo",
    url: "/media/grupos/turquesa/t1.jpeg",
    thumbnailUrl: "/media/grupos/turquesa/t1.jpeg",
    groupColor: "turquesa",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "rojo-1",
    title: "R1",
    type: "photo",
    url: "/media/grupos/rojo/r1.jpeg",
    thumbnailUrl: "/media/grupos/rojo/r1.jpeg",
    groupColor: "rojo",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "verde-limon-1",
    title: "Vl1",
    type: "photo",
    url: "/media/grupos/verde-limon/vl1.jpeg",
    thumbnailUrl: "/media/grupos/verde-limon/vl1.jpeg",
    groupColor: "verde-limon",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "azul-gris-1",
    title: "Ag1",
    type: "photo",
    url: "/media/grupos/azul-gris/ag1.jpeg",
    thumbnailUrl: "/media/grupos/azul-gris/ag1.jpeg",
    groupColor: "azul-gris",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "rosado-1",
    title: "Rs1",
    type: "photo",
    url: "/media/grupos/rosado/rs1.jpeg",
    thumbnailUrl: "/media/grupos/rosado/rs1.jpeg",
    groupColor: "rosado",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "morado-1",
    title: "M1",
    type: "photo",
    url: "/media/grupos/morado/m1.jpeg",
    thumbnailUrl: "/media/grupos/morado/m1.jpeg",
    groupColor: "morado",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "cafe-1",
    title: "C1",
    type: "photo",
    url: "/media/grupos/cafe/c1.jpeg",
    thumbnailUrl: "/media/grupos/cafe/c1.jpeg",
    groupColor: "cafe",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "verde-1",
    title: "V1",
    type: "photo",
    url: "/media/grupos/verde/v1.jpeg",
    thumbnailUrl: "/media/grupos/verde/v1.jpeg",
    groupColor: "verde",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "celeste-1",
    title: "Ce1",
    type: "photo",
    url: "/media/grupos/celeste/ce1.jpeg",
    thumbnailUrl: "/media/grupos/celeste/ce1.jpeg",
    groupColor: "celeste",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "negro-1",
    title: "N1",
    type: "photo",
    url: "/media/grupos/negro/n1.jpeg",
    thumbnailUrl: "/media/grupos/negro/n1.jpeg",
    groupColor: "negro",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  },
  {
    id: "vino-1",
    title: "Vi1",
    type: "photo",
    url: "/media/grupos/vino/vi1.jpeg",
    thumbnailUrl: "/media/grupos/vino/vi1.jpeg",
    groupColor: "vino",
    aspectRatio: "landscape",
    likes: 0,
    date: "2026-08-31",
  }
];

export const GENERATED_COUNT = {
  total: 16,
  groups: 14,
  general: 2,
};
